---
- name: Install unattended-upgrades
  become: True
  apt:
    name:
      - unattended-upgrades

- name: Configure unattended-upgrades
  become: True
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
  with_items:
    - 10periodic
    - 50unattended-upgrades
